# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-03 04:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_type', models.CharField(choices=[('FAT', 'ft'), ('STUPID', 'sd'), ('DUMB', 'db')], default='ft', max_length=2)),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserTrackings',
                'verbose_name': 'UserTracking',
            },
        ),
    ]
